name: Daily Scraper

on:
  schedule:
    - cron: "30 2 * * *"  # Runs daily at 02:30 UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  scrape-job:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        uses: astral-sh/setup-uv@v5

      - name: Commit and Push Changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git pull origin main  # Prevents conflicts
          git add .
          git commit -m "Daily update [skip ci]" || exit 0
          git push origin main
